# -*- coding: utf-8 -*-
"""hight weight

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsgJpxYFbAjSzxWqpxZDEctOy63NraOg
"""

import pandas as pd

import numpy as np

import seaborn as sns

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

df=pd.read_csv("/content/sample_data/weight-height.csv")

df.head()

df.info()

df.describe()

df.tail()

df.info()

df.shape

df.isnull().sum()

sns.heatmap(df.isnull())
plt.show()

sns.histplot(df['Height'])
plt.show()

df.boxplot(column='Weight')
plt.show()

plt.hist(df['Weight'])
plt.show()

plt.hist(df['Weight'],bins=20,rwidth=0.80)
plt.show()

df.info()

df.tail()

df.describe()

df.Gender.value_counts()

from sklearn.linear_model import LinearRegression

df.columns

sns.scatterplot(x='Height',y='Weight',data=df)
plt.show()

x=df[['Height']]
y=df['Weight']

model=LinearRegression()

model.fit(x,y)

model.predict([[70]])

print("Score:", model.score(x,y))